# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build KCC for windows with docker

on:
  workflow_dispatch:
  push:
    branches: [ command_line_exe_windows ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: 3.11
#          cache: 'pip'
#      - name: Install python dependencies
#        run: |
#          python -m pip install --upgrade pip setuptools wheel pyinstaller
#          pip install -r requirements.txt
#      - name: build binary
#        run: |
#          pyi-makespec -F -i icons\\comic2ebook.ico -n KCC_test -w --noupx kcc.py
      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .
          spec: ./KCC_test.spec
      - name: upload build
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: dist/windows/*.exe
#      - name: Release
#        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/')
#        with:
#          prerelease: true
#          generate_release_notes: true
#          files: |
#            CHANGELOG.md
#            LICENSE.txt
#            dist/*.exe