# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build KCC for mac os

on:
  push:
    tags:
      - "v*.*.*"

    # Don't trigger if it's just a documentation update
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '**.yml'
      - '**.sh'
      - 'docs/**'
      - 'Dockerfile'
      - 'LICENSE'
      - '.gitattributes'
      - '.gitignore'
      - '.dockerignore'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'pip'
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel pyinstaller
          pip install -r requirements.txt
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install -g appdmg
      - name: build binary
        run: |
          python setup.py build_binary
      - name: upload build
        uses: actions/upload-artifact@v3
        with:
          name: mac-os-build
          path: dist/*.dmg
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          generate_release_notes: true
          files: |
            CHANGELOG.md
            LICENSE.txt
            dist/*.dmg