name: Publish Python distributions to PyPI and TestPyPI

on:
  push:
    tags:
      - "v*.*.*"
    
    # Don't trigger if it's just a documentation update
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '**.yml'
      - '**.sh'
      - 'docs/**'
      - 'Dockerfile'
      - 'LICENSE'
      - '.gitattributes'
      - '.gitignore'
      - '.dockerignore'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Initialize Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        cache: 'pip'
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel pyinstaller
        pip install -r requirements.txt
    - name: Build Dist
      run: |
        python setup.py sdist
    - name: Release On TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        skip_existing: true
        verbose: true
        print_hash: true
